from __future__ import annotations

from typing import Protocol

from backend.domain.core.constants.rbac import SystemRole
from backend.domain.core.entities.base import TypeID
from backend.domain.core.entities.user import User


class UsersPort(Protocol):
    async def add(self, entity: User) -> None: ...

    async def get(self, entity_id: TypeID) -> User | None: ...

    async def delete(self, entity: User) -> None: ...

    async def assign_role_to_user(self, *, user_id: TypeID, role: SystemRole) -> None: ...

    async def revoke_role_from_user(self, *, user_id: TypeID, role: SystemRole) -> None: ...

    async def get_user_roles(self, *, user_id: TypeID) -> set[SystemRole]: ...

    async def list_user_ids_by_role(self, *, role: SystemRole) -> list[TypeID]: ...
